---
- name: transport | Configuration | Ensure ipsec config
  template:
    src: ipsec.conf
    dest: /etc/ipsec.conf
    mode: 0644
    owner: root
    group: root
  notify: IPSec restart

- name: Transport | Configuration | Ensure secrets file
  ansible.builtin.copy:
    force: yes
    dest: /etc/ipsec.secrets
    content: |
      {{ ipsec_transport_left }} {{ ipsec_transport_right }} : PSK "{{ ipsec_transport_psk_secret }}"
    mode: '0600'
  notify: IPSec secrets reload
