---
- name: VPN | Installation | Install additional packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - iptables-persistent
    - moreutils
    - dnsutils
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: VPN | Installation | Enable verse repositories
  command: "add-apt-repository {{ item }}"
  with_items:
    - universe
    - restricted
    - multiverse
  register: task_result
  until: task_result is success
  changed_when: false
  retries: 3
  delay: 2

- name: VPN | Installation | Install latest version of openswan
  package:
    name:
      - language-pack-en
      - strongswan
      - libstrongswan-standard-plugins
      - strongswan-libcharon
      - libcharon-extra-plugins
      - libcharon-extauth-plugins
      - uuid-runtime
      - libtss2-tcti-tabrmd0
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
