conn site-a
  auto=start
  keyexchange=ikev2
  authby=psk

  left={{ ipsec_tunnel_left }}
  leftsubnet={{ ipsec_tunnel_leftsubnet }}

  right={{ ipsec_tunnel_right }}
  rightsubnet={{ ipsec_tunnel_rightsubnet }}

  ike=aes256-sha512-ecp521!
  esp=aes256gcm16-ecp521!

  ikelifetime=86400s
  lifetime=3600s

  dpdaction=restart
  dpddelay=30s
  dpdtimeout=120s
